//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Spiridonov Maxim @taijased
//

import UIKit

class ___VARIABLE_productName:identifier___ViewModel {
    
    
    private var items: [String]?
    
    func fetchItems(completion: @escaping() -> ()) {
        self?.items = ["items 1", "items 2", "items 2"]
        completion()
    }
    
    func numberOfRowsInSection() -> Int {
        return items?.count ?? 0
    }
    
    func titleForCell(atIndexPath indexPath: IndexPath) -> String {
        guard let items = items else { return "" }
        return items[indexPath.row]
    }
}
